using UnityEngine;
using UnityEngine.SceneManagement; // Added for SceneManager
using UnityEngine.UI; // Added for UI Slider

public class SplashEffects : MonoBehaviour
{
    [Header("Logo Animation")]
    public Transform logo; // Inspector mein "Logo (RectTransform)" assign karo
    public float logoScaleSpeed = 0.1f; // Jaise teri image mein - speed control duration
    public Vector3 maxLogoScale = new Vector3(9f, 4f, 1f); // X9 Y4 Z1 jaise image mein

    [Header("Tyre Rotation")]
    public Transform tyre; // Inspector mein "Tyre Image (RectTransform)" assign karo
    public float tyreRotationSpeed = -360f; // -360 for clockwise (peeche ghumne ke liye)
    public Slider loadingBar; // Assign UI Slider for loading progress

    [Header("Smoke Settings")]
    public float smokeEmitRate = 40f; // Kitna dense smoke
    public float smokeLifetime = 4f; // Kitna der tak dikhe
    public Vector3 smokeOffset = new Vector3(0f, -0.3f, 0f); // Tyre ke neeche se nikle

    [Header("Splash Duration")]
    public float delayAfterFullScale = 0f; // Full scale ke baad kitna wait (sec) - smooth end

    private ParticleSystem smokePS;
    private bool logoFullyScaled = false;
    private bool splashEnded = false;

    void Start()
    {
        // Logo ko bilkul chhota kar do start mein
        if (logo != null)
        {
            logo.localScale = Vector3.one * 0.01f; // Zero se thoda upar, warna invisible
        }

        // Smoke khud banao - koi particle manually add mat karna
        CreateAndSetupSmoke();
        if (loadingBar != null) {
            loadingBar.minValue = 0;
            loadingBar.maxValue = 1;
            loadingBar.value = 0;
        }
    }

    void CreateAndSetupSmoke()
    {
        // Smoke GameObject banao tyre ka child
        GameObject smokeGO = new GameObject("AutoGeneratedSmoke");
        if (tyre != null)
        {
            smokeGO.transform.SetParent(tyre);
            smokeGO.transform.localPosition = smokeOffset;
            smokeGO.transform.localRotation = Quaternion.identity;
            smokeGO.transform.localScale = Vector3.one;
        }
        else
        {
            smokeGO.transform.SetParent(transform);
            smokeGO.transform.localPosition = smokeOffset;
        }

        // ParticleSystem add karo
        smokePS = smokeGO.AddComponent<ParticleSystem>();

        // Main Module setup (purple glowing smoke)
        var main = smokePS.main;
        main.duration = 999f; // Continuous
        main.loop = true;
        main.startLifetime = smokeLifetime;
        main.startSpeed = 0.1f; // Slow start, velocity se move
        main.startSize = 0.2f;
        main.startSize3D = false; // 2D for UI better
        main.maxParticles = 3000;
        main.simulationSpace = ParticleSystemSimulationSpace.Local; // Tyre ke saath ghume
        main.gravityModifier = -0.1f; // Thoda neeche pull, realistic

        // Emission: Continuous rate
        var emission = smokePS.emission;
        emission.enabled = true;
        emission.rateOverTime = smokeEmitRate;

        // Shape: Circle tyre ke around se nikle (burnout style) - EDGE emission
        var shape = smokePS.shape;
        shape.enabled = true;
        shape.shapeType = ParticleSystemShapeType.Circle;
        shape.radius = 0.4f; // Tyre size match karo
        shape.radiusThickness = 0.01f; // EDGE se nikle (bahut patla ring)
        shape.arc = 360f; // Full circle

        // Renderer: Glowing additive + UI sorting fix
        var rendererPS = smokePS.GetComponent<ParticleSystemRenderer>();
        rendererPS.renderMode = ParticleSystemRenderMode.Billboard;
        rendererPS.lengthScale = 1.5f;
        rendererPS.velocityScale = 1f;
        rendererPS.sortingLayerName = "Default"; // UI Canvas ke liye
        rendererPS.sortingOrder = -1; // Peeche rahe (logo/tyre ke peeche)

        // Additive material banao glow ke liye (purple nebula jaise)
        Shader additiveShader = Shader.Find("Particles/Additive");
        if (additiveShader != null)
        {
            Material smokeMat = new Material(additiveShader);
            smokeMat.SetColor("_TintColor", new Color(1f, 0.2f, 0.8f, 1f)); // Magenta-purple base
            rendererPS.material = smokeMat;
        }

        // Velocity over Lifetime: Peeche + upar jaaye, swirl
        var velocity = smokePS.velocityOverLifetime;
        velocity.enabled = true;
        velocity.space = ParticleSystemSimulationSpace.Local;
        velocity.x = new ParticleSystem.MinMaxCurve(-0.3f, 0.3f); // Side swirl
        velocity.y = new ParticleSystem.MinMaxCurve(0.2f, 0.8f); // Upar rise
        velocity.z = new ParticleSystem.MinMaxCurve(-0.8f, -0.3f); // Peeche nikal jaaye

        // Color over Lifetime: Bright purple se fade to transparent
        var colorModule = smokePS.colorOverLifetime;
        colorModule.enabled = true;
        Gradient colorGradient = new Gradient();
        colorGradient.SetKeys(
            new GradientColorKey[] {
                new GradientColorKey(new Color(1f, 0.1f, 1f), 0.0f), // Bright magenta
                new GradientColorKey(new Color(0.6f, 0f, 1f), 0.4f),   // Purple
                new GradientColorKey(new Color(0.3f, 0f, 0.7f), 0.8f)  // Dark blue-purple
            },
            new GradientAlphaKey[] {
                new GradientAlphaKey(1.0f, 0.0f),
                new GradientAlphaKey(0.7f, 0.4f),
                new GradientAlphaKey(0.0f, 1.0f)
            }
        );
        colorModule.color = colorGradient;

        // Size over Lifetime: Chhote se bade ho jaaye phir shrink
        var sizeModule = smokePS.sizeOverLifetime;
        sizeModule.enabled = true;
        AnimationCurve sizeCurve = new AnimationCurve(
            new Keyframe(0f, 0.1f),
            new Keyframe(0.4f, 2.0f),
            new Keyframe(0.8f, 1.5f),
            new Keyframe(1f, 0.3f)
        );
        sizeModule.size = new ParticleSystem.MinMaxCurve(1f, sizeCurve);

        // Rotation over Lifetime: Spin for wispy look
        var rotation = smokePS.rotationOverLifetime;
        rotation.enabled = true;
        rotation.separateAxes = true;
        rotation.z = new ParticleSystem.MinMaxCurve(-180f, 180f); // Z-axis spin (2D)

        // Noise: Swirling turbulence (tera image jaise curly smoke)
        var noiseModule = smokePS.noise;
        noiseModule.enabled = true;
        noiseModule.strength = 0.25f;
        noiseModule.frequency = 1.2f;
        noiseModule.scrollSpeed = 0.5f;

        // Start emission
        smokePS.Play(true);
    }

    void Update()
    {
        // Tyre clockwise rotate (-360 fast) - hamesha chalte rahe
        if (tyre != null)
        {
            tyre.Rotate(Vector3.forward, tyreRotationSpeed * Time.deltaTime);
        }

        // Logo scale up smooth - jab full ho jaye, next scene
        if (logo != null && !splashEnded)
        {
            logo.localScale = Vector3.Lerp(logo.localScale, maxLogoScale, Time.deltaTime * logoScaleSpeed);

            // Check if FULL scale ho gaya (close enough)
            if (!logoFullyScaled && Vector3.Distance(logo.localScale, maxLogoScale) < 0.1f)
            {
                logoFullyScaled = true;
                // Thoda wait kar ke smooth end
                Invoke(nameof(LoadNextScene), delayAfterFullScale);
            }
            // Update loading bar based on logo scaling progress
        if (loadingBar != null && logo != null)
        {
            float progress = Mathf.Clamp01(logo.localScale.x / maxLogoScale.x);
            loadingBar.value = progress;
        }
    }
    }

    void LoadNextScene()
    {
        splashEnded = true;
        // Next scene auto load (Build Settings mein splash scene 0 hona chahiye, next 1)
        SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex + 1);
    }
}